/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author Sahani
 */
//import java.sql.*;
public class AddViewUpdate extends javax.swing.JFrame {

    /**
     * Creates new form AddViewUpdate
     */
    public AddViewUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbview = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btPatient = new javax.swing.JButton();
        btEmployee = new javax.swing.JButton();
        btTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btUWard = new javax.swing.JButton();
        btPayment = new javax.swing.JButton();
        btCheckedDoc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btVPatient = new javax.swing.JButton();
        btVEmployee = new javax.swing.JButton();
        btVtest = new javax.swing.JButton();
        btVward = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbview.setFont(new java.awt.Font("Mongolian Baiti", 0, 22)); // NOI18N
        tbview.setMaximumSize(new java.awt.Dimension(500, 500));
        tbview.setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel2.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 1500));
        jPanel2.setLayout(null);

        btPatient.setBackground(new java.awt.Color(51, 51, 255));
        btPatient.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btPatient.setForeground(new java.awt.Color(255, 255, 255));
        btPatient.setText("Patient");
        btPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPatientActionPerformed(evt);
            }
        });
        jPanel2.add(btPatient);
        btPatient.setBounds(10, 40, 150, 60);

        btEmployee.setBackground(new java.awt.Color(51, 51, 255));
        btEmployee.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btEmployee.setText("Employee");
        btEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(btEmployee);
        btEmployee.setBounds(10, 150, 150, 60);

        btTest.setBackground(new java.awt.Color(51, 51, 255));
        btTest.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btTest.setForeground(new java.awt.Color(255, 255, 255));
        btTest.setText("Test");
        btTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestActionPerformed(evt);
            }
        });
        jPanel2.add(btTest);
        btTest.setBounds(10, 270, 150, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/plain-white-background.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 180, 400);

        btLogout.setBackground(new java.awt.Color(255, 51, 51));
        btLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setText("Log Out");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btLogout);
        btLogout.setBounds(543, 10, 130, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/hospital-management-system.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 0, 510, 400);

        tbview.addTab("Add", jPanel2);

        jPanel3.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(1500, 1500));
        jPanel3.setLayout(null);

        btUWard.setBackground(new java.awt.Color(51, 51, 255));
        btUWard.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btUWard.setForeground(new java.awt.Color(255, 255, 255));
        btUWard.setText("Ward");
        btUWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUWardActionPerformed(evt);
            }
        });
        jPanel3.add(btUWard);
        btUWard.setBounds(10, 40, 220, 50);

        btPayment.setBackground(new java.awt.Color(51, 51, 255));
        btPayment.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btPayment.setForeground(new java.awt.Color(255, 255, 255));
        btPayment.setText("payment  Details");
        btPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaymentActionPerformed(evt);
            }
        });
        jPanel3.add(btPayment);
        btPayment.setBounds(10, 140, 220, 60);

        btCheckedDoc.setBackground(new java.awt.Color(51, 51, 255));
        btCheckedDoc.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btCheckedDoc.setForeground(new java.awt.Color(255, 255, 255));
        btCheckedDoc.setText("Checked Doctor");
        btCheckedDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckedDocActionPerformed(evt);
            }
        });
        jPanel3.add(btCheckedDoc);
        btCheckedDoc.setBounds(10, 250, 220, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/hospital-management-system.jpg"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(240, 0, 450, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/plain-white-background.jpg"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 0, 240, 400);

        tbview.addTab("Update", jPanel3);

        jPanel4.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel4.setPreferredSize(new java.awt.Dimension(1500, 1500));
        jPanel4.setLayout(null);

        btVPatient.setBackground(new java.awt.Color(51, 51, 255));
        btVPatient.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btVPatient.setForeground(new java.awt.Color(255, 255, 255));
        btVPatient.setText("Patient");
        btVPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVPatientActionPerformed(evt);
            }
        });
        jPanel4.add(btVPatient);
        btVPatient.setBounds(10, 30, 140, 60);

        btVEmployee.setBackground(new java.awt.Color(51, 51, 255));
        btVEmployee.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btVEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btVEmployee.setText("Employee");
        btVEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVEmployeeActionPerformed(evt);
            }
        });
        jPanel4.add(btVEmployee);
        btVEmployee.setBounds(10, 120, 140, 60);

        btVtest.setBackground(new java.awt.Color(51, 51, 255));
        btVtest.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btVtest.setForeground(new java.awt.Color(255, 255, 255));
        btVtest.setText("Test ");
        btVtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVtestActionPerformed(evt);
            }
        });
        jPanel4.add(btVtest);
        btVtest.setBounds(10, 210, 140, 60);

        btVward.setBackground(new java.awt.Color(51, 51, 255));
        btVward.setFont(new java.awt.Font("Mongolian Baiti", 1, 22)); // NOI18N
        btVward.setForeground(new java.awt.Color(255, 255, 255));
        btVward.setText("Ward");
        btVward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVwardActionPerformed(evt);
            }
        });
        jPanel4.add(btVward);
        btVward.setBounds(10, 300, 140, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/hospital-management-system.jpg"))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(170, -10, 520, 410);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/plain-white-background.jpg"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 170, 400);

        tbview.addTab("View", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tbview, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbview, javax.swing.GroupLayout.PREFERRED_SIZE, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//view patient's details
    private void btVPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVPatientActionPerformed
        ViewPaient Vpat = new ViewPaient();
        Vpat.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btVPatientActionPerformed
//view employee details
    private void btVEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVEmployeeActionPerformed
        Viewemployee vemp = new Viewemployee();
        vemp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVEmployeeActionPerformed
//view test details
    private void btVtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVtestActionPerformed
        ViewTest vtes = new ViewTest();
        vtes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVtestActionPerformed
//view ward details
    private void btVwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVwardActionPerformed
        ViewWard vwar = new ViewWard();
        vwar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVwardActionPerformed
//Add test details
    private void btTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestActionPerformed
        Tests tes = new Tests();
        tes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btTestActionPerformed
//Add employee details
    private void btEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmployeeActionPerformed
        empNtLogin emp = new empNtLogin();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btEmployeeActionPerformed
//Add patient's details
    private void btPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPatientActionPerformed
        guardianDetails gud = new guardianDetails();
        gud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPatientActionPerformed
//Add the doctors checked the each patient
    private void btCheckedDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckedDocActionPerformed
        CheckedDoc ch = new CheckedDoc();
        ch.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btCheckedDocActionPerformed
//Add payement details
    private void btPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaymentActionPerformed
        PaymentDetails payd = new PaymentDetails();
        payd.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btPaymentActionPerformed
//Add ward
    private void btUWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUWardActionPerformed
        Ward war = new Ward();
        war.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btUWardActionPerformed
//logout from the account
    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        login log = new login();
        log.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddViewUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCheckedDoc;
    private javax.swing.JButton btEmployee;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btPatient;
    private javax.swing.JButton btPayment;
    private javax.swing.JButton btTest;
    private javax.swing.JButton btUWard;
    private javax.swing.JButton btVEmployee;
    private javax.swing.JButton btVPatient;
    private javax.swing.JButton btVtest;
    private javax.swing.JButton btVward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane tbview;
    // End of variables declaration//GEN-END:variables
}
