/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahani
 */
public class AdminDetails extends javax.swing.JFrame {

    /**
     * Creates new form AdminDetails
     */
    public AdminDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblpsd = new javax.swing.JLabel();
        lblConpsd = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConPassword = new javax.swing.JPasswordField();
        btSubmit = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        lblAdmin.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblAdmin.setText("Administrator");
        jPanel1.add(lblAdmin);
        lblAdmin.setBounds(136, 11, 132, 27);

        lblName.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        lblName.setText("User Name");
        jPanel1.add(lblName);
        lblName.setBounds(34, 70, 82, 21);

        lblpsd.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        lblpsd.setText("Password");
        jPanel1.add(lblpsd);
        lblpsd.setBounds(34, 103, 69, 21);

        lblConpsd.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        lblConpsd.setText("Confirm Password");
        jPanel1.add(lblConpsd);
        lblConpsd.setBounds(36, 136, 135, 21);
        jPanel1.add(txtName);
        txtName.setBounds(175, 72, 131, 20);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(175, 105, 131, 20);
        jPanel1.add(txtConPassword);
        txtConPassword.setBounds(175, 136, 131, 20);

        btSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btSubmit);
        btSubmit.setBounds(243, 227, 95, 31);

        btBack.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        jPanel1.add(btBack);
        btBack.setBounds(36, 252, 63, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 390, 330);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//go to the employee details filling form
    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        EmployeeDetails emp = new EmployeeDetails();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed
//submit the details
    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        String name = txtName.getText();
        char[] pass = txtPassword.getPassword();
        char[] cpass = txtConPassword.getPassword();
        //if try to submit without user name
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "User Name field is Empty");
            //if try to submit without password
        } else if (pass.length == 0) {
            JOptionPane.showMessageDialog(null, "Password field is Empty");
            //if try to submit without confirming the password
        } else if (cpass.length == 0) {
            JOptionPane.showMessageDialog(null, "Confirm password field is Empty");
            //if password and confirm passsword doesnot matched
        } else if (!(Arrays.equals(pass, cpass))) {
            JOptionPane.showMessageDialog(null, "confirmed password not matched with the password");

        } else {
            SuccessR suc = new SuccessR();
            suc.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_btSubmitActionPerformed
        try {
//get the id of the guardian which was enetered last
            Statement stat = Database.getStatement();
            ResultSet res = stat.executeQuery("SELECT id FROM employee ORDER BY id DESC LIMIT 1");
            int id = 0;
            while (res.next()) {
                id = res.getInt("employee.id");

            }
//connect to the database and insert the data to the database
            stat.executeUpdate("INSERT INTO admin(user_name,password,employee_id) "
                    + "VALUES('" + txtName.getText() + "','" + txtPassword.getText() + "','" + id + "')");
            //stat.executeUpdate("INSERT INTO Guardian(Patient_id) VALUES('"+txtNIC.getText()+"')");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblConpsd;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblpsd;
    private javax.swing.JPasswordField txtConPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
