/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author Sahani
 */
public class LogDoc extends javax.swing.JFrame {

    /**
     * Creates new form LogDoc
     */
    public LogDoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtAdtest = new javax.swing.JButton();
        BtViTest = new javax.swing.JButton();
        BtViewpat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtAdtest.setBackground(new java.awt.Color(51, 51, 255));
        BtAdtest.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtAdtest.setForeground(new java.awt.Color(255, 255, 255));
        BtAdtest.setText("Add Test");
        BtAdtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAdtestActionPerformed(evt);
            }
        });
        jPanel1.add(BtAdtest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 70));

        BtViTest.setBackground(new java.awt.Color(51, 51, 255));
        BtViTest.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtViTest.setForeground(new java.awt.Color(255, 255, 255));
        BtViTest.setText("View Test");
        BtViTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtViTestActionPerformed(evt);
            }
        });
        jPanel1.add(BtViTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 70));

        BtViewpat.setBackground(new java.awt.Color(51, 51, 255));
        BtViewpat.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtViewpat.setForeground(new java.awt.Color(255, 255, 255));
        BtViewpat.setText("View patient");
        BtViewpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtViewpatActionPerformed(evt);
            }
        });
        jPanel1.add(BtViewpat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/plain-white-background.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 390));

        btLogOut.setBackground(new java.awt.Color(255, 51, 51));
        btLogOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btLogOut.setText("Log Out");
        btLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/Nota-de-Corte-Enfermagem-ProUni-2017.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 450, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Add a test
    private void BtAdtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAdtestActionPerformed
        TestD te = new TestD();
        te.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtAdtestActionPerformed
//view the test details
    private void BtViTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtViTestActionPerformed
        ViewTestD vt = new ViewTestD();
        vt.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtViTestActionPerformed
//view patient's details
    private void BtViewpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtViewpatActionPerformed
        ViewPatientD vp = new ViewPatientD();
        vp.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtViewpatActionPerformed
//go to the login page
    private void btLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutActionPerformed
        login lo = new login();
        lo.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* inSet the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdtest;
    private javax.swing.JButton BtViTest;
    private javax.swing.JButton BtViewpat;
    private javax.swing.JButton btLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
