/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahani
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        psfLogin = new javax.swing.JPasswordField();
        btUser = new javax.swing.JButton();
        btNewUser = new javax.swing.JButton();
        lblLogAs = new javax.swing.JLabel();
        cmbLogAs = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblLogin.setText("User Login");
        jPanel1.add(lblLogin);
        lblLogin.setBounds(210, 0, 190, 50);

        lblUserName.setFont(new java.awt.Font("Mongolian Baiti", 0, 20)); // NOI18N
        lblUserName.setText("User Name");
        jPanel1.add(lblUserName);
        lblUserName.setBounds(100, 130, 100, 30);

        lblPassword.setFont(new java.awt.Font("Mongolian Baiti", 0, 20)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(100, 160, 100, 40);
        jPanel1.add(txtUserName);
        txtUserName.setBounds(210, 130, 180, 30);
        jPanel1.add(psfLogin);
        psfLogin.setBounds(210, 170, 180, 30);

        btUser.setBackground(new java.awt.Color(153, 255, 255));
        btUser.setFont(new java.awt.Font("Sitka Subheading", 1, 22)); // NOI18N
        btUser.setText("Login");
        btUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserActionPerformed(evt);
            }
        });
        jPanel1.add(btUser);
        btUser.setBounds(190, 240, 230, 50);

        btNewUser.setBackground(new java.awt.Color(204, 204, 255));
        btNewUser.setFont(new java.awt.Font("Sitka Subheading", 1, 22)); // NOI18N
        btNewUser.setText("New User?");
        btNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewUserActionPerformed(evt);
            }
        });
        jPanel1.add(btNewUser);
        btNewUser.setBounds(190, 310, 230, 50);

        lblLogAs.setFont(new java.awt.Font("Mongolian Baiti", 0, 20)); // NOI18N
        lblLogAs.setText("Log As");
        jPanel1.add(lblLogAs);
        lblLogAs.setBounds(100, 80, 110, 40);

        cmbLogAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Receptionist", "Doctor" }));
        jPanel1.add(cmbLogAs);
        cmbLogAs.setBounds(210, 80, 180, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/UserAvatar.svg.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(490, 100, 100, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/download (4).jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 50, 390, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/khan-academy.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 450);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//if login in the first time 
    private void btNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewUserActionPerformed
        EmployeeDetails empd = new EmployeeDetails();
        empd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btNewUserActionPerformed
//select the user type and check whether password matches
    private void btUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserActionPerformed
        String user_name = txtUserName.getText();
        String pass_word = String.valueOf(psfLogin.getPassword());
        System.out.println(pass_word);
        if (cmbLogAs.getSelectedItem() == "Administrator") {
            try {

                Statement s = Database.getStatement();
                ResultSet rs = s.executeQuery("SELECT user_name,password FROM admin WHERE user_name='"
                        + "" + txtUserName.getText() + "'");
                while (rs.next()) {
                    String getPass_word = rs.getString("password");
                    System.out.println(getPass_word);

                    if (pass_word.equals(getPass_word)) {
                        AddViewUpdate ad = new AddViewUpdate();
                        ad.setVisible(true);
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "Sorry. password is incorrect");
                    }
                }
            } catch (Exception ex) {

                ex.printStackTrace();
            }
        } else if (cmbLogAs.getSelectedItem() == "Doctor") {
            try {

                Statement s = Database.getStatement();
                ResultSet rs = s.executeQuery("SELECT user_name,password FROM doctor WHERE user_name='"
                        + "" + txtUserName.getText() + "'");
                while (rs.next()) {
                    String getPass_word = rs.getString("password");
                    System.out.println(getPass_word);

                    if (pass_word.equals(getPass_word)) {
                        LogDoc ad = new LogDoc();
                        ad.setVisible(true);
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "Sorry. password is incorrect");
                    }
                }
            } catch (Exception ex) {

                ex.printStackTrace();
            }
        } else if (cmbLogAs.getSelectedItem() == "Receptionist") {
            try {

                Statement s = Database.getStatement();
                ResultSet rs = s.executeQuery("SELECT user_name,password FROM receptionist WHERE user_name='"
                        + "" + txtUserName.getText() + "'");
                while (rs.next()) {
                    String getPass_word = rs.getString("password");
                    System.out.println(getPass_word);

                    if (pass_word.equals(getPass_word)) {
                        LogReceip ad = new LogReceip();
                        ad.setVisible(true);
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "Sorry. password is incorrect");
                    }
                }
            } catch (Exception ex) {

                ex.printStackTrace();
            }
        }


    }//GEN-LAST:event_btUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNewUser;
    private javax.swing.JButton btUser;
    private javax.swing.JComboBox<String> cmbLogAs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogAs;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField psfLogin;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
