/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author Sahani
 */
public class LogReceip extends javax.swing.JFrame {

    /**
     * Creates new form LogReceip
     */
    public LogReceip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtAdPatient = new javax.swing.JButton();
        BtVPatient = new javax.swing.JButton();
        BtUpPWard = new javax.swing.JButton();
        BtVWard = new javax.swing.JButton();
        BtCheckDoc = new javax.swing.JButton();
        btVEmp = new javax.swing.JButton();
        btLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtAdPatient.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtAdPatient.setText("Add Patient");
        BtAdPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAdPatientActionPerformed(evt);
            }
        });
        jPanel1.add(BtAdPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 45, 205, 67));

        BtVPatient.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtVPatient.setText("View Patient");
        BtVPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVPatientActionPerformed(evt);
            }
        });
        jPanel1.add(BtVPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 205, 67));

        BtUpPWard.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtUpPWard.setText("Update Ward");
        BtUpPWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUpPWardActionPerformed(evt);
            }
        });
        jPanel1.add(BtUpPWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 155, 205, 67));

        BtVWard.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtVWard.setText("View Ward");
        BtVWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVWardActionPerformed(evt);
            }
        });
        jPanel1.add(BtVWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 205, 67));

        BtCheckDoc.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        BtCheckDoc.setText("Checked Doctor");
        BtCheckDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCheckDocActionPerformed(evt);
            }
        });
        jPanel1.add(BtCheckDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 269, 205, 67));

        btVEmp.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        btVEmp.setText("View employee");
        btVEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btVEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 205, 67));

        btLogOut.setBackground(new java.awt.Color(255, 51, 51));
        btLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btLogOut.setText("Log Out");
        btLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/Fotolia_48721026_S.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Go to the checked doctor
    private void BtCheckDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCheckDocActionPerformed
        chekedDocR cD = new chekedDocR();
        cD.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtCheckDocActionPerformed
//Add patient's details
    private void BtAdPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAdPatientActionPerformed
        guardianDetailsR gD = new guardianDetailsR();
        gD.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtAdPatientActionPerformed
//view patient details
    private void BtVPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVPatientActionPerformed
        ViewPatientR VP = new ViewPatientR();
        VP.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtVPatientActionPerformed
//Add ward details
    private void BtUpPWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUpPWardActionPerformed
        WardR WR = new WardR();
        WR.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtUpPWardActionPerformed
//view ward details
    private void BtVWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVWardActionPerformed
        ViewWardR Vw = new ViewWardR();
        Vw.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BtVWardActionPerformed
//view employee details
    private void btVEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVEmpActionPerformed
        ViewEmployeeR vE = new ViewEmployeeR();
        vE.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btVEmpActionPerformed
//logout
    private void btLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutActionPerformed
        login lo = new login();
        lo.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogReceip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogReceip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogReceip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogReceip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogReceip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdPatient;
    private javax.swing.JButton BtCheckDoc;
    private javax.swing.JButton BtUpPWard;
    private javax.swing.JButton BtVPatient;
    private javax.swing.JButton BtVWard;
    private javax.swing.JButton btLogOut;
    private javax.swing.JButton btVEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
