/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.Statement;

/**
 *
 * @author Sahani
 */
public class WardR extends javax.swing.JFrame {

    /**
     * Creates new form WardR
     */
    public WardR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWard = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblNurse = new javax.swing.JLabel();
        lblAvBeds = new javax.swing.JLabel();
        lblOccuBeds = new javax.swing.JLabel();
        spinWNo = new javax.swing.JSpinner();
        txtNurse = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        txtAvBe1 = new javax.swing.JTextField();
        btSubmit = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        txtOcBe = new javax.swing.JTextField();
        btOK = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWard.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblWard.setText("Ward Details");

        lblNo.setFont(new java.awt.Font("Mongolian Baiti", 0, 15)); // NOI18N
        lblNo.setText("Ward No");

        lblName.setFont(new java.awt.Font("Mongolian Baiti", 0, 15)); // NOI18N
        lblName.setText("Ward Name");

        lblNurse.setFont(new java.awt.Font("Mongolian Baiti", 0, 15)); // NOI18N
        lblNurse.setText("Nurse Incharged");

        lblAvBeds.setFont(new java.awt.Font("Mongolian Baiti", 0, 15)); // NOI18N
        lblAvBeds.setText("Available Beds");

        lblOccuBeds.setFont(new java.awt.Font("Mongolian Baiti", 0, 15)); // NOI18N
        lblOccuBeds.setText("Beds Occupied");

        spinWNo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        btSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        btback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        txtOcBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOcBeActionPerformed(evt);
            }
        });

        btOK.setText("ok");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        btUpdate.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        btUpdate.setText("Update");
        btUpdate.setToolTipText("");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblWard))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNo)
                            .addComponent(lblName)
                            .addComponent(lblNurse)
                            .addComponent(btback)
                            .addComponent(lblOccuBeds)
                            .addComponent(lblAvBeds))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinWNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtOcBe, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAvBe1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btOK))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(btUpdate)))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btSubmit)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWard)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNo)
                            .addComponent(spinWNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblName))
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNurse)
                    .addComponent(txtNurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOccuBeds)
                    .addComponent(txtOcBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAvBeds)
                        .addGap(18, 18, 18)
                        .addComponent(btback)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAvBe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSubmit)
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        SuccessR suc = new SuccessR();
        suc.setVisible(true);
        this.dispose();
//connect the database and add details to it
        try {

            Statement stat = Database.getStatement();
            stat.executeUpdate("INSERT INTO ward(no,name,nurse_incharged,oc_beds,av_beds) VALUES('" + spinWNo.getValue() + "','" + txtName1.getText() + "','" + txtNurse.getText() + "','" + txtOcBe.getText() + "','" + txtAvBe1.getText() + "')");
        } catch (Exception e) {
            e.printStackTrace();

            // TODO add your handling code here:
        }
    }//GEN-LAST:event_btSubmitActionPerformed
//go to starting page
    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        LogReceip ad = new LogReceip();
        ad.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btbackActionPerformed

    private void txtOcBeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOcBeActionPerformed

    }//GEN-LAST:event_txtOcBeActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        //calculate the number of available beds 
        String a = txtOcBe.getText();
        int oc = Integer.parseInt(a);
        //System.out.println(b);
        int av = 50 - oc;
        String sav = Integer.toString(av);
        txtAvBe1.setText(sav);
        // TODO add your handling code here:
    }//GEN-LAST:event_btOKActionPerformed
//update the given record
    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        try {

            Statement stat = Database.getStatement();
            stat.executeUpdate("UPDATE ward "
                    + "SET nurse_incharged='" + txtNurse.getText() + "',oc_beds='" + txtOcBe.getText() + "',av_beds='" + txtAvBe1.getText() + "' "
                    + "WHERE no='" + spinWNo.getValue() + "'");

        } catch (Exception ex) {

            ex.printStackTrace();
        }
        SuccessFR suc = new SuccessFR();
        suc.setVisible(true);
        this.dispose();// TODO add your h

        /* try {

            Statement stat = Database.getStatement();
            stat.executeUpdate("INSERT INTO ward(no,name,nurse_incharged,oc_beds,av_beds) VALUES('" + spinWNo.getValue() + "','" + txtName1.getText() + "','"+txtNurse.getText()+"','"+txtOcBe.getText()+"','"+txtAvBe1.getText()+"')");
        } catch (Exception e) {
            e.printStackTrace();
        }// TODO add your handling code here:*/
    }//GEN-LAST:event_btUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WardR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WardR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WardR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WardR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WardR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOK;
    private javax.swing.JButton btSubmit;
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton btback;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvBeds;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNurse;
    private javax.swing.JLabel lblOccuBeds;
    private javax.swing.JLabel lblWard;
    private javax.swing.JSpinner spinWNo;
    private javax.swing.JTextField txtAvBe1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtNurse;
    private javax.swing.JTextField txtOcBe;
    // End of variables declaration//GEN-END:variables
}
